"""Fix DocumentChunk: document field type

Revision ID: cd3842759531
Revises: 3d0a2e9577ea
Create Date: 2026-02-15 07:02:49.700174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd3842759531'
down_revision: Union[str, Sequence[str], None] = '3d0a2e9577ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_id'), 'chat', ['id'], unique=False)
    op.drop_column('chat', 'test_field')
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    op.create_index(op.f('ix_documentchunk_id'), 'documentchunk', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentchunk_id'), table_name='documentchunk')
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.add_column('chat', sa.Column('test_field', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_chat_id'), table_name='chat')
    # ### end Alembic commands ###
